version: "3"
services:
  pyspark:
    image: jupyter/pyspark-notebook
    hostname: &name pyspark
    container_name: *name
    ports:
      - 8888:8888
      - 4040:4040
      - 4041:4041
    volumes:
      - ./src/pregel.ipynb:/home/jovyan/work/pregel.ipynb
      - ./src/helper.py:/home/jovyan/work/helper.py
    environment:
      - NOTEBOOK_ARGS=--NotebookApp.token='' --NotebookApp.password=''
